### ISSUE TITLE
Add `dropHead` and `dropTail`.

### ISSUE THREAD

**Issue by jussi-kalliokoski** [jussi-kalliokoski/trine#10]
See #9 - `dropHead(n)` would basically be the equivalent of `slice(n)`, and `dropTail(n)` the equivalent of `slice(0, length - n)`.

**Comment by kievechua** [comment]
What's the direction of this project, are you creating api base on Lodash and Underscore or not?

Lodash has [drop](https://lodash.com/docs#drop) and [dropRight](https://lodash.com/docs#dropRight)

**Comment by jussi-kalliokoski** [comment]
The lodash/underscore API is definitely an inspiration, however I've decided to do some naming slightly differently because unlike lodash, trine operates mostly on iterators instead of collections. Hence for example the prefix `Right` doesn't quite semantically fit because there is no right, just an end. As such, the terminology commonly used for streams (e.g. bash) makes more sense. However, Unix CLI tools often do too many things making it harder to reason about them, while with Trine I attempt to make the "do one thing and do it well" as absolute as possible, which is why `head` or `tail` don't have overloads that take instead of dropping.

This brings nice symmetry as well:

* `take` -> filter out items that don't satisfy the condition.
* `drop` -> filter out items that satisfy the condition.
* `takeWhile` -> filter out items after the condition is first not satisfied.
* `dropWhile` -> filter out items before the condition is first satisfied.
* `head` (could also be named `takeHead`) -> take only N first items.
* `tail` (could also be named `takeTail`) -> take only N last items.
* `dropHead` -> take all except N first items.
* `dropTail` -> take all except N last items.

**Comment by kievechua** [comment]
> however I've decided to do some naming slightly differently because unlike lodash, trine operates mostly on iterators instead of collections. Hence for example the prefix Right doesn't quite semantically fit because there is no right, just an end. As such, the terminology commonly used for streams (e.g. bash) makes more sense.

That sound even better, just what to understand more about this project and what direction you are going, keep up the good work :)
