### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kievechua** [jussi-kalliokoski/trine#29]
@jussi-kalliokoski is there any roadmap document we can refer?

Another question is this libraries supporting browser?

**Comment by jussi-kalliokoski** [comment]
> is there any roadmap document we can refer?

This issue tracker is currently the informal roadmap. I attempt to maintain a milestone for tracking each upcoming release, e.g. https://github.com/jussi-kalliokoski/trine/milestones/0.1.0 :)

> Another question is this libraries supporting browser?

Yes, the library works in browsers as well. However it requires using [webpack](http://webpack.github.io/), [browserify](http://browserify.org/) or some other CommonJS-compatible module bundler. The browser support depends on [babel-runtime](https://www.npmjs.com/package/babel-runtime), but IIRC that should still support browsers up to IE8 for most features.

**Comment by kievechua** [comment]
> This issue tracker is currently the informal roadmap. I attempt to maintain a milestone for tracking each upcoming release, e.g. https://github.com/jussi-kalliokoski/trine/milestones/0.1.0 :)

Sound cool, it should get very organized.

> Yes, the library works in browsers as well. However it requires using webpack, browserify or some other CommonJS-compatible module bundler. The browser support depends on babel-runtime, but IIRC that should still support browsers up to IE8 for most features.

Hope browser side testing is in the roadmap too :P

**Comment by jussi-kalliokoski** [comment]
> Hope browser side testing is in the roadmap too :P

Yes, I have an account on BrowserStack I use for my other OSS projects and intend to integrate it to Trine as well! :P
