### ISSUE TITLE
Explicitly Mention Babel and Babel-Runtime in Installation in README

### ISSUE THREAD

**Issue by bsusensjackson** [jussi-kalliokoski/trine#36]
Very interesting library.  Please explicitly state these requirements in your installation documentation.

**Comment by bsusensjackson** [comment]
Would probably help out with #24

**Comment by jussi-kalliokoski** [comment]
It used to be documented, but the [next version](https://github.com/jussi-kalliokoski/trine/milestones/0.1.0) has it explicitly in the dependencies: #26. Hoping to release 0.1.0 in the coming days. :)
