### ISSUE TITLE
"Doesn't deserve"?

### ISSUE THREAD

**Issue by KyleAMathews** [jussi-kalliokoski/trine#5]
If you want people who "gasp" like Javascript to use your library, you might want to eliminate your snark.

**Comment by thom-nic** [comment]
I think most people who use javascript have a love/hate relationship.  I'll use this library (or not) based on its technical merits, snark or not.

**Comment by JaCraig** [comment]
I don't know. I actually just starred this thing and plan to try it out because of the Batman reference...

**Comment by KyleAMathews** [comment]
nvm, grumpy morning. Carry on as before :)

**Comment by jussi-kalliokoski** [comment]
Yeah, no snark intended, just a cultural pun reference to Batman and the love/hate relationship that most people have with JS. :)

**Comment by barneycarroll** [comment]
I'm boycotting this library despite its patent pertinence to my regular struggles until you sort your attitude out ;)

I think the slogan is incredibly pertinent. It's not as if I'm any where near as experienced with any other language — JS is my bread and butter — but I don't at all mind it being done down in this context. My general opinion is that `this` is a code smell and prototypal extension is mostly an anti-pattern. ES6 came along and made functional programming more awesome on the one hand with arrows and parameter sugar, but on the other hand set is back years by furnishing `class` and `super` — Javascript has essentially continued to dig itself a hole.

Trine is the salvation of `this`_and_ a shot in the arm for functional programming, which until now I would have said was a contradiction in terms. So describing Trine as the salvation of a language which has been digging itself into this whole for so long isn't too blasphemous in my eyes.

If you really think ES6 doesn't have a historic problem that Trine addresses, you're probably better off using Ramda or Lodash. It's not as if the README doesn't address alienatives.

**Comment by jussi-kalliokoski** [comment]
@barneycarroll I don't think I understand whether you like Trine or not. :D

> I'm boycotting this library

I'm sad to hear that. :/

> until you sort your attitude out [...] JS is my bread and butter

No attitude here, JS is my bread and butter as well and as such my goal is to merely make working with it as nice as possible.

> but on the other hand set is back years by furnishing `class` and `super`

On some days I agree and on some I disagree. I don't like classes, but I'd take ES6 classes over the "every library's own pattern for classes in JS" any day. However, Trine takes no stance at classes, it provides helpers for values and instances alike.

> If you really think ES6 doesn't have a historic problem that Trine addresses, you're probably better off using Ramda or Lodash. It's not as if the README doesn't address alienatives.

I'm afraid I don't quite understand this paragraph, sorry. :/

**Comment by ryanberckmans** [comment]
@barneycarroll is right. The batman reference is cute but not working for you. You're losing X% of your community due to an epsilon-sized mistake.

No offense man, this is just a business thing. I really like Trine, but community strength is a primary factor  in library selection. There's evidence that Trine's community is diminished by the snarky slogan (if batman-lovable).

Guys like me wonder - wow, if this guy is shedding community on something as easy as a slogan, what about the hard stuff? It honestly is a deciding factor. Utility libraries shouldn't employ controversial PR strategies. Boring is good in this department.

**Comment by jussi-kalliokoski** [comment]
@ryanberckmans you're absolutely right, thank you. Will fix. Sorry to anyone who's been offended. :)

**Comment by ryanberckmans** [comment]
> A utility library for modern JavaScript.

Love it.

> Trine is a utility library geared at tapping the full potential of functional programming in JS, in the vein of lodash, underscore and Ramda.

"Full potential" is justified and nice branding. Thanks for this.

**Comment by barneycarroll** [comment]
@jussi-kalliokoski sorry, that was a tongue in cheek joke followed by a few paragraphs in total support of the original message and the library as a whole. If that didn't come across, then I guess we really should avoid humour in programming :)

**Comment by MiracleBlue** [comment]
@barneycarroll Picking up tone on the internet can be tricky sometimes :P

I'm a total fan of the batman thing.  It doesn't even come close to snark.  I'm starting to think people are getting way too sensitive these days.  Oh well.

**Comment by jussi-kalliokoski** [comment]
> sorry, that was a tongue in cheek joke followed by a few paragraphs in total support of the original message and the library as a whole.

ahh, thought so, but couldn't be sure :P
