### ISSUE TITLE
Mention compatible libraries

### ISSUE THREAD

**Issue by tomekwi** [jussi-kalliokoski/trine#55]
There’s **[curry-this](https://github.com/stoeffel/chickencurry/tree/v3)** – almost ready.

And there’s **[this-is-truthy](https://github.com/tomekwi/this-is-truthy)** since 5 minutes ago :)

How about mentioning that in the readme?

**Comment by jussi-kalliokoski** [comment]
Yes, also [mori-ext](https://github.com/roobie/mori-ext)

**Comment by jussi-kalliokoski** [comment]
Maybe it should be a wiki page though with a link from the README, that way it's easier to maintain and contribute to.

**Comment by tomekwi** [comment]
:+1:

**Comment by jussi-kalliokoski** [comment]
Decided to put them into the README anyway in hopes of getting some easy-off first contributions. :P

**Comment by tomekwi** [comment]
:+1:
